[package]
name = "nom-hello"
version = "0.1.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]

[dependencies]
nom = "3.2.0"
serde_derive = "1.0.15"
serde_json = "1.0.4"
serde = "1.0.15"
clap = "2.26.2"